# Generated by Django 4.2 on 2023-05-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgv', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('date', models.TextField()),
                ('gender', models.TextField()),
                ('address', models.TextField()),
                ('ethnic', models.TextField()),
                ('degree', models.TextField()),
            ],
        ),
    ]
