# Generated by Django 4.2 on 2023-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('gender', models.TextField()),
                ('department', models.TextField()),
                ('majors', models.TextField()),
                ('classroom', models.TextField()),
            ],
        ),
    ]
